var holeInfo = [
	"<p>Skip the disc straight down the road into the emergency beacon. <em>Obviously, do not activate the beacon.</em></p><p>Stop if cars are passing.</p><p>Move your disc if a car may threaten to crush it.</p><p>Hole-in-one has been achieved (2016).</p>",
	"2!",
	"3!",
	"4!",
	"5!",
	"6?",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"16",
	"17",
	"18"
];